#!/bin/bash


conda activate xsuite
which python

CURRDIR=/home/kparasch/workspace/eclouds-in-xsuite/LHC_top_energy/Buildup/simulations/LHC6.8TeV_v1_DR23R5_27_sey1.35_1.20e11ppb_test
export CURRDIR

echo $PYTHONPATH

# Copy input and executable
cp ${PYTHONPATH}/PyECLOUD/main.py .

cp ${CURRDIR}/*.input .
cp ${CURRDIR}/*.beam .
cp ${CURRDIR}/*.mat .

python main.py

#save result
cp Pyecltest.mat ${CURRDIR}
